# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.3
        with:
          node-version: 12.18.2 
      
      # Instalar as dependências NPN/Yarn
      - name: Install dependencies
        run: yarn
      
      # Executar a build
      - name: Run Build
        run: yarn build
        
      # Copiar pasta "dist" para o servidor (vamos usar https://github.com/appleboy/scp-action)
      - name: copy dist to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "dist"
          target: "test"
        
    # Substituir o código existente na pasta "dist" pelo novo código
    # Executar "yarn" no servidor
    # Executar as migrations do TypeORM
    # Restartar no servidor Node.js
